name: Tests

on:
  push:
    branches:
      - main
      - master
      - develop
      - workos

  pull_request:
    branches:
      - main
      - master
      - develop
      - workos

jobs:
  ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4, 8.5]

    services:
      mysql:
        image: mysql:8.4

        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Node Dependencies
        run: npm install

      - name: Configure Flux License
        run: composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Configure Testing Database
        run: |
          php artisan config:clear

          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=testing" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: php artisan test